nuoma/nuoma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rooms.urls', namespace='rooms')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

nuoma/rooms/urls.py
from django.urls import path
from . import views

app_name = 'rooms'

urlpatterns = [
    path('', views.room_list, name= 'room_list'),
    path('<slug:category_slug>/', views.room_list, name='room_list_by_category'),
    path('<int:id>/<slug:slug>/', views.room_detail, name='room_detail'),
]

nuoma/rooms/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('title',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('rooms:room_list_by_category', args=[self.slug])


class Property(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    description = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.title


class Room(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='rooms',
                                 on_delete=models.CASCADE)
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    visible = models.BooleanField(default=False)
    properties1 = models.ManyToManyField(Property, null= True)

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('rooms:room_detail',
                       args=[self.id, self.slug])




class RoomImage(models.Model):
    image = models.ImageField(upload_to='room/')
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=150, blank=True)
    order = models.PositiveBigIntegerField(null=True)
    room = models.ForeignKey(Room, default=None, related_name='images', on_delete=models.PROTECT)


    def __str__(self):
        return self.title

nuoma/rooms/forms.py
from django import forms


# class DateForm(forms.Form):
#     date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])

nuoma/rooms/views.py
from django.shortcuts import render, get_object_or_404
from rooms.models import Room, Category, RoomImage


def room_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    rooms = Room.objects.filter(visible=True)
    imag = RoomImage.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        rooms = Room.objects.filter(category=category,  visible=True)

        imag = RoomImage.objects.filter(room_id=3)
    return render(request,
                  'hotel/rooms/list.html',
                  {'category': category,
                   'categories': categories,
                   'rooms': rooms,
                   'imag': imag})


def room_detail(request, id, slug):

    room = get_object_or_404(Room,
                             id=id,
                             slug=slug,
                             visible=True)
    r_id = room.id
    images = RoomImage.objects.filter(room_id=r_id)
    prop = room.properties1.all()

    return render(request,
                  'hotel/rooms/detail.html',
                  {'room': room,
                   'images': images,
                   'prop': prop})

nuoma/rooms/templates/hotel/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block tilte %}  My hotel  {% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
    <div id="header">
    <span class="logo">HOTEL</span>

    <ul class="menu">
      <li >
        <a href="#">Image button </a>
      </li>
    </ul>
    </div>

      <div id="content">
    {% block content %}
    {% endblock %}
      </div>
</body>
</html>

nuoma/rooms/templates/hotel/rooms/detail.html
{% extends "hotel/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ room.title }}{% else %}Rooms{% endif %}
{% endblock %}

{% block content %}
    <div class="room-detail">

    {% if images %}
        {% for im in images %}
                 <img src="{{ im.image.url }}">
        {% endfor %}
    {% else %}
            <img src="{% static 'img/no_image.png' %} ">
        {% endif %}


    <h1>{{ room.title }}</h1>
    <h2>
      <a href="{{ room.category.get_absolute_url }}">
        {{ room.category }}
      </a>
    </h2>
    <p class="price">${{ room.price }}</p>
       kambario id {{room.id}}
    {{ room.description|linebreaks }}

       {% for p in prop %}
               <ul> P {{ p }} </ul>
        {% endfor %}
  </div>


{% endblock %}

nuoma/rooms/templates/hotel/rooms/list.html
{% extends "hotel/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Rooms{% endif %}
{% endblock %}

{% block content %}
   <div id="sidebar">
       <h3>Categories</h3>
       <ul>
           <li {% if not category %}class="selected"{% endif %}>
               <a href="{% url "rooms:room_list" %}">All</a>
           </li>
           {% for c in categories %}
           <li {% if category.slug == c.slug %}class="selected" {% endif %}>
               <a href="{{ c.get_absolute_url }}">{{ c.title }}</a>
           </li>
           {% endfor %}
       </ul>
   </div>
   <div id="main" class="room-list">
        <h1>{% if category %}{{ category.title }}{% else %} Rooms
            {% endif %}</h1>
            {% for room in rooms %}
                <div class="item">
                    <a href="{{ room.get_absolute_url }}">
                        <img src="{% if room.photo_id.photo %}{{ room.photo_id.photo.url }}{%else %}
                     {% static "img/no_image.png" %} {% endif %}"></a>
                    <a href="{{ room.get_absolute_url }}">{{ room.title }}</a>

                   <br>
                    ${{ room.price }}
                     {% for i in imag %}

                         image:  {{  i.image }}
                         id   :  {{room.id}}
                     {% endfor %}
                </div>

            {% endfor %}
   </div>
{% endblock %}